version: "3.8"

services:
  metabase:
    image: metabase/metabase:v0.48.6
    restart: unless-stopped
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabaseappdb
      - MB_DB_PORT=5432
      - MB_DB_USER=name
      - MB_DB_PASS=password
      - MB_DB_HOST=my-database-host
    ports:
      - "3000:3000"
