services:
  metabase:
    image: metabase/metabase:latest
    restart: unless-stopped
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - "5679:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - data:/metabase-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  data:
