services:
  metabase:
    image: metabase/metabase:latest
    restart: unless-stopped
    ports:
      - "5433:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - metabase_data:/metabase.db

volumes:
  metabase_data:
